### ISSUE TITLE
Concatenating Strings

### ISSUE THREAD

**Issue by aewing** [getopenmono/mono_framework#4]
I am having trouble concatenating mono::String instances within my httpHandleData method. I would like to concatenate the bodyChunks into a complete response, but can't seem to make that happen. Does anyone have an example of this?

**Comment by stoffera** [comment]
Even though you closed the issue, here is an example:

``` cpp
mono::String concated = mono::String::Format("%s%s",monoStr1(), monoStr2());
```

Note that if the source string are `mono::String` (not a generic C string), then you must apply the execute operator `()` in the `Format` argument list.

**Comment by aewing** [comment]
Thank you. I was missing the execute operator, but managed to figure it out.
