### ISSUE TITLE
DateTime::toUtcTime doesn't work with LOCAL_TIME_ZONE

### ISSUE THREAD

**Issue by malaire** [getopenmono/mono_framework#9]
The incrementation of `hours` in `DateTime::toUtcTime` doesn't work when it would go to previous/next day because constructor trims the `hours` value.

This should probably use `addHours` instead.

**Comment by stoffera** [comment]
Yes, this is indeed an issue. I will change it to your suggestion.

**Comment by stoffera** [comment]
Fixed in 39b44c5
